plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
    namespace 'com.joya.lib_download'
    compileSdk 36

    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }

    defaultConfig {
        minSdk 24
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

}

dependencies {
    api project(':filedownloader')
}

publishing {
    publications {
        release(MavenPublication) {
            groupId = project.group.toString()
            artifactId = 'lib_download'
            version = project.version.toString()
            afterEvaluate { from components.release }
        }
    }
}
